### ISSUE TITLE
lxd gets sigkilled on reboot

### ISSUE THREAD

**Issue by C0rn3j** [maikelwever/lxd#5]
Hiya, 
opening an issue here, not sure if the AUR page is more proper.

The package has the following issue - https://github.com/lxc/lxd/issues/4277#issuecomment-368037914

**Comment by dann1** [comment]
On ArchLinux lxd puts 1 min and 30 sec extra time to reboot.

**Comment by maikelwever** [comment]
Some containers don't shut down properly (I'm having this issue with Debian 9 containers), some time ago someone proposed to sigkill the remaning processes because earlier the system wouldn't shutdown at all because the wait time was infinite.

The default wait time on Ubuntu's LXD packaging is ~10 minutes, which IMO is way too long for desktop/laptop use.

If you have a workaround or suggestion how to fix this, please open a PR.

`sudo systemctl stop lxd normally works fine.` -> This is not the case for me, especially with Debian 9 containers. The init process in the container stays in shutdown state for me.

**Comment by maikelwever** [comment]
Please re-open if this issue persists with v3.8

**Comment by C0rn3j** [comment]
Looks to be fixed, thanks a lot!

**Comment by maikelwever** [comment]
You're welcome, and apologies it took a while to fix this.

The fix was sourced from the lxd-git package on AUR, so credits to them where due ;)

**Comment by C0rn3j** [comment]
Actually lxd, not lxd-git. But hey, at least it's fixed, better late than never.
